{% set name = "brainrender-napari" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainrender-napari-{{ version }}.tar.gz
  sha256: f28250a0d544db4543b04ac5ec417339e1e2e4880a470591a1b356d96a66c100

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9.0
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - bg-atlasapi
    - napari >=0.4.18
    - numpy
    - python >=3.9.0
    - qtpy

test:
  imports:
    - brainrender_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/brainrender-napari
  summary: A napari plugin to render BrainGlobe atlases and associated data as layers.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainrender-napari

extra:
  recipe-maintainers:
    - alessandrofelder
    - goanpeca
    - jaimergp
